// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Work Today Tomorrow and always..",
                            Created = new DateTime(2024, 9, 5, 13, 6, 45, 671, DateTimeKind.Local).AddTicks(3008),
                            Title = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Travel Today Tomorrow and always..",
                            Created = new DateTime(2024, 9, 5, 13, 6, 45, 671, DateTimeKind.Local).AddTicks(3360),
                            Title = "Travel"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Explore Today Tomorrow and always..",
                            Created = new DateTime(2024, 9, 5, 13, 6, 45, 671, DateTimeKind.Local).AddTicks(3362),
                            Title = "Explore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
